services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: adopet_user
      POSTGRES_PASSWORD: adopet_password
      POSTGRES_DB: adopet_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  test:
    build: .
    command: pytest
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DJANGO_SETTINGS_MODULE: config.settings
    volumes:
      - .:/code
    depends_on:
      - db

volumes:
  postgres_data: