# Generated by Django 5.0.3 on 2024-10-07 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('size', models.CharField(choices=[('SM', 'Small'), ('M', 'Medium'), ('B', 'Big')], default='SM', max_length=2)),
                ('description', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('adopted', models.BooleanField(default=False)),
                ('image', models.URLField()),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adopet.shelter')),
            ],
        ),
    ]
