# Generated by Django 5.0.3 on 2024-10-08 01:05

import adopet.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopet', '0004_alter_adoption_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.CharField(max_length=10, validators=[adopet.validators.validate_age]),
        ),
        migrations.AlterField(
            model_name='pet',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('B', 'Big'), ('SM', 'Small/Medium'), ('MB', 'Medium/Big')], default='SM', max_length=2),
        ),
    ]
