# Generated by Django 5.0.3 on 2024-10-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopet', '0005_alter_pet_age_alter_pet_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='adopted',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
