# Generated by Django 5.0.3 on 2024-10-08 12:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopet', '0006_alter_pet_adopted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='password',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
