# Generated by Django 5.0.3 on 2024-10-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopet', '0007_alter_tutor_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.CharField(max_length=10),
        ),
    ]
