# Generated by Django 5.0.3 on 2024-10-10 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopet', '0008_alter_pet_age'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutor',
            options={'ordering': ['name']},
        ),
    ]
