# Generated by Django 5.0.3 on 2024-10-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopet', '0010_alter_shelter_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('B', 'Big'), ('SM', 'Small/Medium'), ('MB', 'Medium/Big')], default='SM', max_length=100),
        ),
    ]
