# Generated by Django 5.0.3 on 2024-10-10 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopet', '0011_alter_pet_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adoption',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='adoption',
            old_name='data',
            new_name='date',
        ),
    ]
