# Generated by Django 5.0.3 on 2024-10-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopet', '0012_alter_adoption_options_alter_pet_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='size',
            field=models.CharField(choices=[('P', 'pequeno'), ('M', 'médio'), ('G', 'grande'), ('MG', 'médio/grande')], default='SM', max_length=100),
        ),
    ]
