# Generated by Django 5.0.3 on 2024-10-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopet', '0013_alter_pet_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='size',
            field=models.CharField(choices=[('pequeno', 'P'), ('médio', 'M'), ('grande', 'G'), ('médio/grande', 'MG')], default='SM', max_length=100),
        ),
    ]
