# Generated by Django 5.0.3 on 2024-10-12 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopet', '0014_alter_pet_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={},
        ),
        migrations.AlterModelOptions(
            name='shelter',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tutor',
            options={},
        ),
    ]
