name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]
        
    env:
       SECRET_KEY: ${{ secrets.SECRET_KEY }}
       POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
       POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
       POSTGRES_DB: ${{ secrets.POSTGRES_DB }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run Database
      run: |
        docker compose up -d db

    - name: Run Web
      run: |
        docker compose up -d web
        docker compose logs web

    - name: Check Web Logs
      run: docker compose logs web

    - name: Wait for Web to be ready
      run: sleep 10
  
    - name: Run Lint
      run: |
          docker compose exec web black .
          docker compose exec web flake8 .
 
    - name: Run Tests
      run: |
         docker compose run test
